		{
			name="#APPNAME_LC#",
			description="#APP_DESC#",
			protocol="dynamiclinklibrary",
			aliases=
			{
				"#APPNAME_LC#_alias1",
				"#APPNAME_LC#_alias2",
				"#APPNAME_LC#_alias3",
			},
			--validateHandshake=true,
			--default=true,
		},
