#!/bin/sh

#remove username and group
id crtmpserver
if [ "$?" = "0" ]
then
        userdel crtmpserver
        if [ "$?" != "0" ]
        then
                echo "Unable to delete crtmpserver user"
                exit 1
        fi
	exit 0
else
	exit 0
fi

