#!/bin/sh

#create username
id crtmpserver
if [ "$?" = "0" ]
then
	userdel crtmpserver
	if [ "$?" != "0" ]
	then
		echo "Unable to delete crtmpserver user"
		exit 1
	fi
fi

adduser --no-create-home --shell /bin/sh --disabled-password --gecos "C++ RTMP Server" crtmpserver
for i in `find /opt/crtmpserver/applications -type d -name mediaFolder`; do chown -R crtmpserver:crtmpserver $i;done
chmod 755 /etc/init.d/crtmpserver
chown root:root /etc/init.d/crtmpserver
exit $?


